version: "3"

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image:  mariadb:v1
    container_name: mariadb
    env_file: .env
    expose:
      - "3306"
    volumes:
      -   mariadb_vol:/var/lib/mysql
    restart: always
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    image:  wordpress:v1
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    expose:
      - "9000"
    volumes:
      - wordpress_vol:/var/www/html
    restart: unless-stopped
    networks:
      - inception
    #restart: unless-stopped

  nginx:
    build:
      context: ./requirements/nginx
    image:  nginx:v1
    container_name: nginx
    depends_on:
      - wordpress
    ports: 
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
    restart: unless-stopped
    networks:
      - inception

volumes:
  wordpress_vol:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress # mkdir -p /home/${USER}/data/wordpress
  mariadb_vol:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb # mkdir -p /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge